version: '3.8'

services:
  node:
    image: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:$VERSION
    networks:
      - traefik-public
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: pg
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'false'
      TYPEORM_ENTITIES: build/models/*.js 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${APP_NAME}.rule=Host(`backend.${APP_NAME}.${CI_ENVIRONMENT_SLUG}.softtero.com`)"
        - "traefik.http.routers.${APP_NAME}.entrypoints=http"
        - "traefik.http.routers.${APP_NAME}-secured.rule=Host(`backend.${APP_NAME}.${CI_ENVIRONMENT_SLUG}.softtero.com`)"
        - "traefik.http.routers.${APP_NAME}-secured.entrypoints=https"
        - "traefik.http.routers.${APP_NAME}-secured.tls.certresolver=le"
        - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
        - "traefik.http.routers.${APP_NAME}.middlewares=${APP_NAME}-redirect"
        - "traefik.http.middlewares.${APP_NAME}-redirect.redirectscheme.scheme=https"
        - "traefik.constraint-label=traefik-public"
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure

  pg:
    image: postgres:13
    ports:
      - 1011:5432
    networks:
      - traefik-public
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.platform.os == linux
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true

volumes:
  db-data:
    name: ${STACK_NAME}-${APP_NAME}-backend-data