CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) UNIQUE,
    bps VARCHAR(30) UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('ADMIN', 'SOCIO', 'POSTULANTE')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuario_identificador_check CHECK (email IS NOT NULL OR bps IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS postulantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id),
    nombre_completo VARCHAR(160) NOT NULL,
    cedula_identidad VARCHAR(30) NOT NULL UNIQUE,
    telefono VARCHAR(40) NOT NULL,
    zona_residencia VARCHAR(120) NOT NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS perfiles_laborales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulante_id BIGINT NOT NULL REFERENCES postulantes(id),
    nombre VARCHAR(120) NOT NULL,
    disponibilidad_horaria VARCHAR(20) NOT NULL CHECK (disponibilidad_horaria IN ('FULL_TIME', 'PART_TIME')),
    tiene_vehiculo BOOLEAN NOT NULL DEFAULT FALSE,
    ultimo_empleo VARCHAR(200),
    descripcion_experiencia TEXT
);

CREATE TABLE IF NOT EXISTS rubros_empleo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rubro VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS perfil_rubros (
    perfil_id BIGINT NOT NULL REFERENCES perfiles_laborales(id) ON DELETE CASCADE,
    rubro_id BIGINT NOT NULL REFERENCES rubros_empleo(id),
    PRIMARY KEY (perfil_id, rubro_id)
);

INSERT INTO rubros_empleo (nombre_rubro) VALUES
    ('Ventas'), ('Repartidores'), ('Administracion'), ('Choferes'), ('Contabilidad'),
    ('Recepcionista'), ('Mecanica'), ('Logistica'), ('Construccion'), ('Informatica')
ON CONFLICT (nombre_rubro) DO NOTHING;