-- Modelo de dominio CCISJ: socios, cuotas, ofertas, CV y comunicados.
-- Las reglas no estructurales (morosidad, pagos exactos, un rubro principal, etc.)
-- se aplican en la capa de servicio; aca quedan constraints e indices de apoyo.

ALTER TABLE usuarios
    ADD COLUMN IF NOT EXISTS fecha_baja TIMESTAMP WITH TIME ZONE;

ALTER TABLE postulantes
    ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
    ADD COLUMN IF NOT EXISTS genero VARCHAR(30)
        CHECK (genero IS NULL OR genero IN ('FEMENINO', 'MASCULINO', 'PREFIERO_NO_ESPECIFICAR')),
    ADD COLUMN IF NOT EXISTS estado_civil VARCHAR(20)
        CHECK (estado_civil IS NULL OR estado_civil IN ('SOLTERO', 'CASADO', 'UNION_LIBRE', 'DIVORCIADO', 'VIUDO'));

ALTER TABLE perfiles_laborales
    DROP CONSTRAINT IF EXISTS perfiles_laborales_disponibilidad_horaria_check;

ALTER TABLE perfiles_laborales
    ADD CONSTRAINT perfiles_laborales_disponibilidad_horaria_check
        CHECK (disponibilidad_horaria IN ('FULL_TIME', 'PART_TIME', 'INDEFINIDO'));

CREATE TABLE direcciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR(160) NOT NULL,
    numero VARCHAR(20),
    localidad VARCHAR(120) NOT NULL
);

CREATE TABLE socios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios(id),
    direccion_id BIGINT REFERENCES direcciones(id),
    rubro_id BIGINT REFERENCES rubros_empleo(id),
    razon_social VARCHAR(200) NOT NULL,
    rut VARCHAR(20) UNIQUE,
    telefono VARCHAR(40),
    email_contacto VARCHAR(254),
    giro VARCHAR(160),
    estado_morosidad VARCHAR(30) NOT NULL DEFAULT 'AL_DIA'
        CHECK (estado_morosidad IN ('AL_DIA', 'DEUDA_A_VENCER', 'DEUDA_VENCIDA', 'INACTIVO')),
    es_directivo BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_alta DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE cuotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    socio_id BIGINT NOT NULL REFERENCES socios(id),
    periodo DATE NOT NULL,
    monto NUMERIC(12, 2) NOT NULL CHECK (monto > 0),
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'PAGADA', 'FORZOSO', 'ANULADA')),
    UNIQUE (socio_id, periodo)
);

CREATE TABLE pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuota_id BIGINT NOT NULL UNIQUE REFERENCES cuotas(id),
    monto_cobrado NUMERIC(12, 2) NOT NULL CHECK (monto_cobrado > 0),
    fecha_emision DATE NOT NULL,
    nro_cobranza_externo VARCHAR(80),
    observaciones TEXT,
    modificado_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ofertas_empleo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    socio_id BIGINT NOT NULL REFERENCES socios(id),
    rubro_id BIGINT NOT NULL REFERENCES rubros_empleo(id),
    titulo VARCHAR(180) NOT NULL,
    descripcion TEXT NOT NULL,
    cargo VARCHAR(120),
    tipo_contrato VARCHAR(20)
        CHECK (tipo_contrato IS NULL OR tipo_contrato IN ('EFECTIVO', 'TEMPORARIA', 'ZAFRA', 'PASANTIA')),
    disponibilidad_horaria VARCHAR(20) NOT NULL DEFAULT 'FULL_TIME'
        CHECK (disponibilidad_horaria IN ('FULL_TIME', 'PART_TIME', 'INDEFINIDO')),
    vacantes INTEGER NOT NULL DEFAULT 1 CHECK (vacantes >= 1),
    fecha_publicacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVA'
        CHECK (estado IN ('ACTIVA', 'PAUSADA', 'CERRADA', 'VENCIDA'))
);

CREATE TABLE postulaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulante_id BIGINT NOT NULL REFERENCES postulantes(id),
    oferta_id BIGINT NOT NULL REFERENCES ofertas_empleo(id),
    fecha TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rubro_principal BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (postulante_id, oferta_id)
);

CREATE UNIQUE INDEX postulaciones_un_rubro_principal
    ON postulaciones (postulante_id)
    WHERE rubro_principal = TRUE;

CREATE TABLE cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulante_id BIGINT NOT NULL UNIQUE REFERENCES postulantes(id),
    resumen TEXT,
    ruta_archivo_cv VARCHAR(500)
);

CREATE TABLE experiencias_laborales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_id BIGINT NOT NULL REFERENCES cvs(id) ON DELETE CASCADE,
    nombre_empresa VARCHAR(160) NOT NULL,
    cargo VARCHAR(120) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    tareas TEXT,
    contacto_referencia VARCHAR(160)
);

CREATE TABLE formaciones_academicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_id BIGINT NOT NULL REFERENCES cvs(id) ON DELETE CASCADE,
    institucion VARCHAR(160) NOT NULL,
    titulo VARCHAR(160) NOT NULL,
    nivel VARCHAR(40) NOT NULL
        CHECK (nivel IN ('EDUCACION_PRIMARIA', 'EDUCACION_MEDIA_BASICA', 'EDUCACION_MEDIA_SUPERIOR', 'EDUCACION_TERCIARIA', 'OTROS')),
    fecha_inicio DATE,
    fecha_fin DATE,
    en_curso BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE idiomas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE cv_idiomas (
    cv_id BIGINT NOT NULL REFERENCES cvs(id) ON DELETE CASCADE,
    idioma_id BIGINT NOT NULL REFERENCES idiomas(id),
    nivel VARCHAR(10) NOT NULL
        CHECK (nivel IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'NATIVO')),
    PRIMARY KEY (cv_id, idioma_id)
);

CREATE TABLE habilidades_estandar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE cv_habilidades (
    cv_id BIGINT NOT NULL REFERENCES cvs(id) ON DELETE CASCADE,
    habilidad_id BIGINT NOT NULL REFERENCES habilidades_estandar(id),
    PRIMARY KEY (cv_id, habilidad_id)
);

CREATE TABLE comunicados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor_id BIGINT NOT NULL REFERENCES usuarios(id),
    titulo VARCHAR(180) NOT NULL,
    contenido TEXT NOT NULL,
    fecha_publicacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    destinatario VARCHAR(30) NOT NULL DEFAULT 'TODOS'
        CHECK (destinatario IN ('TODOS', 'SOCIOS', 'SOLO_DIRECTIVOS', 'POSTULANTES'))
);

INSERT INTO idiomas (nombre) VALUES
    ('Espanol'), ('Ingles'), ('Portugues'), ('Frances'), ('Italiano')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO habilidades_estandar (nombre) VALUES
    ('Atencion al cliente'), ('Manejo de caja'), ('Paquete Office'),
    ('Conduccion profesional'), ('Trabajo en equipo')
ON CONFLICT (nombre) DO NOTHING;
