ALTER TABLE cvs
    DROP CONSTRAINT IF EXISTS cvs_postulante_id_key;

ALTER TABLE cvs
    ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS nombre_archivo VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mime_type VARCHAR(120),
    ADD COLUMN IF NOT EXISTS size_bytes BIGINT,
    ADD COLUMN IF NOT EXISTS fecha_carga TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS cvs_un_activo_por_postulante
    ON cvs (postulante_id)
    WHERE activo = TRUE;
